//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CercleRoyalEscrimeTournaisien.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGlobal() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CercleRoyalEscrimeTournaisien.Resources.ResourceGlobal", typeof(ResourceGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activités.
        /// </summary>
        public static string Activite_Sujet {
            get {
                return ResourceManager.GetString("Activite_Sujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;escrime est un sport de combat. 3 armes sont utilisées : le fleuret, l&apos;épée et le sabre. Ces 3 armes sont mixtes; individuelle ou par équipes..
        /// </summary>
        public static string Agenda3Armes {
            get {
                return ResourceManager.GetString("Agenda3Armes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous trouverez ici le calendrier téléchargeable sous format word..
        /// </summary>
        public static string AgendaDocumentTelechargeable {
            get {
                return ResourceManager.GetString("AgendaDocumentTelechargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les cours au fleuret sont en bleu, à l&apos;épée en rouge et au sabre en vert. Les séances Parent sont en orange..
        /// </summary>
        public static string CouleurArmesAgenda {
            get {
                return ResourceManager.GetString("CouleurArmesAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Cercle Royal d&apos;Escrime de Tournai vous accueille à l&apos;école de Don Bosco, 37 rue des Augustins..
        /// </summary>
        public static string Horaires_1 {
            get {
                return ResourceManager.GetString("Horaires_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les dimanches de 10h à 12h.
        /// </summary>
        public static string Horaires_10 {
            get {
                return ResourceManager.GetString("Horaires_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour tout renseignement, vous pouvez nous contacter:.
        /// </summary>
        public static string Horaires_11 {
            get {
                return ResourceManager.GetString("Horaires_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Via notre maître d&apos;Armes.
        /// </summary>
        public static string Horaires_12 {
            get {
                return ResourceManager.GetString("Horaires_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Via notre secrétaire.
        /// </summary>
        public static string Horaires_12_secretaire {
            get {
                return ResourceManager.GetString("Horaires_12_secretaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Benoît Lafaut: 0478/34.78.95.
        /// </summary>
        public static string Horaires_13 {
            get {
                return ResourceManager.GetString("Horaires_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Régis Trannoy: 0472/28.97.41.
        /// </summary>
        public static string Horaires_13_secretaire {
            get {
                return ResourceManager.GetString("Horaires_13_secretaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Via mail.
        /// </summary>
        public static string Horaires_14 {
            get {
                return ResourceManager.GetString("Horaires_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à escrime.tournai@gmail.com.
        /// </summary>
        public static string Horaires_15 {
            get {
                return ResourceManager.GetString("Horaires_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici le plan.
        /// </summary>
        public static string Horaires_2 {
            get {
                return ResourceManager.GetString("Horaires_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour chaque groupe, l&apos;entrée se fait par la rue des Augustins..
        /// </summary>
        public static string Horaires_3 {
            get {
                return ResourceManager.GetString("Horaires_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les entraînements se font.
        /// </summary>
        public static string Horaires_4 {
            get {
                return ResourceManager.GetString("Horaires_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mercredis de 18h à 19h30.
        /// </summary>
        public static string Horaires_7 {
            get {
                return ResourceManager.GetString("Horaires_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les vendredis de 18h à 20h.
        /// </summary>
        public static string Horaires_9 {
            get {
                return ResourceManager.GetString("Horaires_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nos Cours.
        /// </summary>
        public static string NosCours {
            get {
                return ResourceManager.GetString("NosCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quelques sites intéressants.
        /// </summary>
        public static string QuelquesSitesInteressants_Sujet {
            get {
                return ResourceManager.GetString("QuelquesSitesInteressants_Sujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agenda des cours d&apos;escrime pour la saison en cours.
        /// </summary>
        public static string TitleAgenda {
            get {
                return ResourceManager.GetString("TitleAgenda", resourceCulture);
            }
        }
    }
}
