//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CercleRoyalEscrimeTournaisien.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceHistorique {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHistorique() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CercleRoyalEscrimeTournaisien.Resources.ResourceHistorique", typeof(ResourceHistorique).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Du 3 au 8 avril 1996.
        /// </summary>
        public static string Historique_Du_3_au_8_avril_1996 {
            get {
                return ResourceManager.GetString("Historique_Du_3_au_8_avril_1996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous la présidence d&apos;Alexandre Walnier, organisation du Championnat du Monde Cadets-Juniors dans le hall &apos;Tournai - Expo&apos;.
        /// </summary>
        public static string Historique_Du_3_au_8_avril_1996_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Du_3_au_8_avril_1996_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En 1935.
        /// </summary>
        public static string Historique_En_1935 {
            get {
                return ResourceManager.GetString("Historique_En_1935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes du 50ème anniversaire.
        /// </summary>
        public static string Historique_En_1935_Content_1 {
            get {
                return ResourceManager.GetString("Historique_En_1935_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En 1936.
        /// </summary>
        public static string Historique_En_1936 {
            get {
                return ResourceManager.GetString("Historique_En_1936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Maître Paenhuysen ayant quitté le CRET, ouvre sa propre salle, rue Duquesnoy. Il faudra attendre 1947 pour que les deux salles soient à nouveau réunies en un seul cercle..
        /// </summary>
        public static string Historique_En_1936_Content_1 {
            get {
                return ResourceManager.GetString("Historique_En_1936_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En mai 1998 et mai 2000.
        /// </summary>
        public static string Historique_En_mai_1998_et_mai_2000 {
            get {
                return ResourceManager.GetString("Historique_En_mai_1998_et_mai_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organisation des Championnats de Belgique Seniors dans la salle ADEPS du &apos;grand large&apos; à Péronnes.
        /// </summary>
        public static string Historique_En_mai_1998_et_mai_2000_Content_1 {
            get {
                return ResourceManager.GetString("Historique_En_mai_1998_et_mai_2000_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 01 avril 1928.
        /// </summary>
        public static string Historique_Le_01_avril_1928 {
            get {
                return ResourceManager.GetString("Historique_Le_01_avril_1928", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de la coupe HENRI KINIF.
        /// </summary>
        public static string Historique_Le_01_avril_1928_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_01_avril_1928_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 01 septembre 1884.
        /// </summary>
        public static string Historique_Le_01_septembre_1884 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1884", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fondation à l&apos;hôtel des Neuf Provinces du cercle de Tournai sous le nom de &apos;Tournai KINIF Club&apos; par le Maître Henri Kinif, ex premier Maître au 3ème Chasseur à Pieds et Maître Van Rodesa, ex premier Maître au 4ème Lanciers..
        /// </summary>
        public static string Historique_Le_01_septembre_1884_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1884_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leur premier élève s&apos;appelle Mr. Connart. Il est employé au chemin de fer..
        /// </summary>
        public static string Historique_Le_01_septembre_1884_Content_2 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1884_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note : on trouve trace à cette époque de l&apos;existence d&apos;autres cercles, par exemple: le cercle des avocats et la section escrime du club vélosport..
        /// </summary>
        public static string Historique_Le_01_septembre_1884_Content_3 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1884_Content_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 01 septembre 1888.
        /// </summary>
        public static string Historique_Le_01_septembre_1888 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous la présidence de Mr. Depotter, le cercle change de nom et devient Cercle d&apos;Escrime Tournaisien.
        /// </summary>
        public static string Historique_Le_01_septembre_1888_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_01_septembre_1888_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 08 mai 1927.
        /// </summary>
        public static string Historique_Le_08_mai_1927 {
            get {
                return ResourceManager.GetString("Historique_Le_08_mai_1927", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes.
        /// </summary>
        public static string Historique_Le_08_mai_1927_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_08_mai_1927_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 12 avril 1903.
        /// </summary>
        public static string Historique_Le_12_avril_1903 {
            get {
                return ResourceManager.GetString("Historique_Le_12_avril_1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes.
        /// </summary>
        public static string Historique_Le_12_avril_1903_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_12_avril_1903_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 20 octobre 1984.
        /// </summary>
        public static string Historique_Le_20_octobre_1984 {
            get {
                return ResourceManager.GetString("Historique_Le_20_octobre_1984", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes du 100ème anniversaire.
        /// </summary>
        public static string Historique_Le_20_octobre_1984_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_20_octobre_1984_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 21 novembre 1927.
        /// </summary>
        public static string Historique_Le_21_novembre_1927 {
            get {
                return ResourceManager.GetString("Historique_Le_21_novembre_1927", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le cercle reçoit le titre de Société Royale et devient Cercle Royal d&apos;Escrime Tournaisien.
        /// </summary>
        public static string Historique_Le_21_novembre_1927_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_21_novembre_1927_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 24 novembre 1964.
        /// </summary>
        public static string Historique_Le_24_novembre_1964 {
            get {
                return ResourceManager.GetString("Historique_Le_24_novembre_1964", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes du 80ème anniversaire.
        /// </summary>
        public static string Historique_Le_24_novembre_1964_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_24_novembre_1964_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 26 janvier 1930.
        /// </summary>
        public static string Historique_Le_26_janvier_1930 {
            get {
                return ResourceManager.GetString("Historique_Le_26_janvier_1930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le cercle &apos;Le Trèfle&apos; se crée. Il est situé à la salle G. Reper à la place Crombez. Il vivra 3 à 4 ans..
        /// </summary>
        public static string Historique_Le_26_janvier_1930_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_26_janvier_1930_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note: dans les années 30-31, il existait au moins 4 cercles à Tournai :.
        /// </summary>
        public static string Historique_Le_26_janvier_1930_Content_2 {
            get {
                return ResourceManager.GetString("Historique_Le_26_janvier_1930_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - 2 militaires : le cercle du 3ème Chasseurs à Pieds et le cercle du 11ème d&apos;Artillerie.
        /// </summary>
        public static string Historique_Le_26_janvier_1930_Content_3 {
            get {
                return ResourceManager.GetString("Historique_Le_26_janvier_1930_Content_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - 2 civils : le C.R.E.T. et le cercle &apos;Le Trèfle&apos;.
        /// </summary>
        public static string Historique_Le_26_janvier_1930_Content_4 {
            get {
                return ResourceManager.GetString("Historique_Le_26_janvier_1930_Content_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 27 avril 1923.
        /// </summary>
        public static string Historique_Le_27_avril_1923 {
            get {
                return ResourceManager.GetString("Historique_Le_27_avril_1923", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes à l&apos;occasion du 50ème anniversaire de l&apos;entrée de Maître Kinif dans la carrière des armes..
        /// </summary>
        public static string Historique_Le_27_avril_1923_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_27_avril_1923_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 29 septembre 1896.
        /// </summary>
        public static string Historique_Le_29_septembre_1896 {
            get {
                return ResourceManager.GetString("Historique_Le_29_septembre_1896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1ère organisation d&apos;un concours international d&apos;escrime. 140 salles de Belgique et de France sont invitées..
        /// </summary>
        public static string Historique_Le_29_septembre_1896_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_29_septembre_1896_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sont inscrits des tireurs de Lille, Roubaix, Tourcoing, Wattrelos, Bruxelles, Anvers, Leuze, Anvaing et Frasnes..
        /// </summary>
        public static string Historique_Le_29_septembre_1896_Content_2 {
            get {
                return ResourceManager.GetString("Historique_Le_29_septembre_1896_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le 30 septembre 1904.
        /// </summary>
        public static string Historique_Le_30_septembre_1904 {
            get {
                return ResourceManager.GetString("Historique_Le_30_septembre_1904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gala d&apos;Armes.
        /// </summary>
        public static string Historique_Le_30_septembre_1904_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Le_30_septembre_1904_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les MAITRES D&apos;ARMES.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1884 à 1927.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_1_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Henri Kinif.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_1_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note: entre 1975 et 1977, l&apos;intérim a été assuré par le Maître de Lessines Jean-Marie Degauque.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_10 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1927 à 1935.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_2_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à René Paenhuysen.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_2_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1936 à 1962.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_3_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Léon Bertrand.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_3_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1962 à 1968.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_4_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Henri Valembois.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_4_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1969 à 1975.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_5_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Léon Bertrand.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_5_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1977 à 1994.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_6_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Michel Demulder.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_6_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 1994 à 2000.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_7_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Olivier Debondt.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_7_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 2000 à 2013.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_8_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérald Williot.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_8_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - de 2014 à nos jours.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_9_1 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Benoît Lafaut.
        /// </summary>
        public static string Historique_Les_MAITRES_D_ARMES_Content_9_2 {
            get {
                return ResourceManager.GetString("Historique_Les_MAITRES_D_ARMES_Content_9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les salles D&apos;armes de Tournai.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A partir de 1884.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_1_1 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A l&apos;hôtel de la Gare, Place Crombez.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_1_2 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A partir de 1924.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_2_1 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au café des 7 étoiles, 3, Rue de la Tête d&apos;Or.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_2_2 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A partir du 01 avril 1961.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_3_1 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans une salle appartenant à la famille Hivre 34 Quai vifquin.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_3_2 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A partir du 27 avril 1987.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_4_1 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans l&apos;immeuble dit &apos;Hôtel Crombez&apos;, 3, Rue Saint-Piat.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_4_2 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A partir du 01 septembre 1997.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_5_1 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans le hall sportif de la C.E.T., dans l&apos;école de Saint-André et maintenant à l&apos;école de Don Bosco.
        /// </summary>
        public static string Historique_Les_salles_D_armes_de_Tournai_Content_5_2 {
            get {
                return ResourceManager.GetString("Historique_Les_salles_D_armes_de_Tournai_Content_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pendant la guerre 40-45.
        /// </summary>
        public static string Historique_Pendant_la_guerre_40_45 {
            get {
                return ResourceManager.GetString("Historique_Pendant_la_guerre_40_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le cercle est fermé en mai 1940 mais reprendra rapidement ses activités, après une demande d&apos;ouverture faite en janvier 1941..
        /// </summary>
        public static string Historique_Pendant_la_guerre_40_45_Content_1 {
            get {
                return ResourceManager.GetString("Historique_Pendant_la_guerre_40_45_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suite à l&apos;ordonnance du 27 décembre 1941 relative à la remise des armes, les autorités allemandes font une inspection le 14 février 1942 dans les locaux du cercle.
        /// </summary>
        public static string Historique_Pendant_la_guerre_40_45_Content_2 {
            get {
                return ResourceManager.GetString("Historique_Pendant_la_guerre_40_45_Content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à et saisissent deux fusils de collection et 4 baïonnettes..
        /// </summary>
        public static string Historique_Pendant_la_guerre_40_45_Content_3 {
            get {
                return ResourceManager.GetString("Historique_Pendant_la_guerre_40_45_Content_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historique.
        /// </summary>
        public static string Historique_Sujet {
            get {
                return ResourceManager.GetString("Historique_Sujet", resourceCulture);
            }
        }
    }
}
